use crate::model::{PrivateRedactionEvent, RedactionEvent, RedactionSummary, SkippedFile};
use anyhow::Result;

pub fn summary_text(summary: &RedactionSummary) -> String {
    let mut lines = vec![
        format!("Files scanned: {}", summary.scanned_files),
        format!("Files redacted: {}", summary.redacted_files),
        format!("Files skipped: {}", summary.skipped_files),
        format!("Redactions: {}", summary.redaction_count),
    ];

    if !summary.by_class.is_empty() {
        lines.push("Redactions by class:".to_string());
        for (class, count) in &summary.by_class {
            lines.push(format!("  {class}: {count}"));
        }
    }

    lines.join("\n")
}

pub fn summary_markdown(summary: &RedactionSummary, skipped: &[SkippedFile]) -> String {
    let mut out = String::new();
    out.push_str("# Safe Bundle Summary\n\n");
    out.push_str("| Metric | Count |\n");
    out.push_str("|---|---:|\n");
    out.push_str(&format!("| Files scanned | {} |\n", summary.scanned_files));
    out.push_str(&format!(
        "| Files redacted | {} |\n",
        summary.redacted_files
    ));
    out.push_str(&format!("| Files skipped | {} |\n", summary.skipped_files));
    out.push_str(&format!("| Redactions | {} |\n", summary.redaction_count));

    if !summary.by_class.is_empty() {
        out.push_str("\n## Redactions by Class\n\n");
        out.push_str("| Class | Count |\n");
        out.push_str("|---|---:|\n");
        for (class, count) in &summary.by_class {
            out.push_str(&format!("| `{class}` | {count} |\n"));
        }
    }

    if !skipped.is_empty() {
        out.push_str("\n## Skipped Files\n\n");
        out.push_str("| Path | Reason |\n");
        out.push_str("|---|---|\n");
        for skipped_file in skipped {
            out.push_str(&format!(
                "| `{}` | {} |\n",
                escape_markdown_table(&skipped_file.path),
                escape_markdown_table(&skipped_file.reason)
            ));
        }
    }

    out.push_str("\n## Limits\n\n");
    out.push_str("This bundle is a developer safety artifact, not a legal de-identification guarantee. It redacts supported high-confidence classes and preserves diagnostic structure where possible.\n");
    out
}

pub fn events_jsonl(events: &[RedactionEvent]) -> Result<String> {
    let mut out = String::new();
    for event in events {
        out.push_str(&serde_json::to_string(event)?);
        out.push('\n');
    }
    Ok(out)
}

pub fn private_events_json(events: &[PrivateRedactionEvent]) -> Result<String> {
    Ok(serde_json::to_string_pretty(events)?)
}

pub fn skipped_jsonl(skipped: &[SkippedFile]) -> Result<String> {
    let mut out = String::new();
    for file in skipped {
        out.push_str(&serde_json::to_string(file)?);
        out.push('\n');
    }
    Ok(out)
}

pub fn readme_text() -> &'static str {
    "Safe support bundle generated by safe-bundle.\n\nThis archive contains redacted files only. It does not contain original files or raw secret values. Review summary.md and redactions.jsonl before sharing publicly.\n"
}

fn escape_markdown_table(input: &str) -> String {
    input.replace('|', "\\|").replace('\n', " ")
}
